name: indoor_localization_demo
description: Indoor localization demo using WiFi fingerprinting and ONNX inference.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  wifi_scan: ^0.4.0+1
  onnxruntime: 1.4.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/Maps/
